### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by bucuram** [AKC23/Harnessing-LLMs-over-transformer-models-for-detecting-Bengali-depressive-text-A-comprehensive-study#1]
Hi,

You did a great work!
How can I get access to the dataset used in your paper?

Thanks,
Ana

**Comment by SR-Sujon** [comment]
Hi, Ana. 
Thanks for reaching out.
We are going to publish the dataset soon.

**Comment by SR-Sujon** [comment]
Hi, Ana.
The dataset is published on ResearchGate today.
Feel free to do more experiments.

Thanks,
Sujon

**Comment by bucuram** [comment]
Thank you!
